define(["libraries/bowser/bowser"],function(t){class e extends Backbone.Controller{initialize(){this.$html=$("html"),this.$window=$(window),this.touch=Modernizr.touchevents,this.screenWidth=this.getScreenWidth(),this.screenHeight=this.getScreenHeight(),this.browser=(t.name||"").toLowerCase(),this.version=(t.version||"").toLowerCase(),this.OS=this.getOperatingSystem().toLowerCase(),this.osVersion=t.osversion||"",this.renderingEngine=this.getRenderingEngine();let e=this.browser.toLowerCase().replace(/msie|internet explorer/,"ie");e=(e=(e+=` version-${this.version} OS-${this.OS} `+this.getAppleDeviceType())+e.replace(".","-").toLowerCase())+" pixel-density-"+this.pixelDensity(),this.$html.addClass(e),console.log(`%c
OS:             ${this.OS}
touch:          ${this.touch}
browser:        ${this.browser}
version:        ${this.version}
renderEngine:   ${this.getRenderingEngine()}

dpr:                ${window.devicePixelRatio}
screenWidth:        ${this.screenWidth}
screenHeight:       ${this.screenHeight}
windowOrientation:  ${window.orientation}
`,"color: blue;")}get orientation(){return this.screenWidth>=this.screenHeight?"landscape":"portrait"}get aspectRatio(){return this.screenWidth/this.screenHeight}getScreenWidth(){return this.isAppleDevice()?this.getAppleScreenWidth():window.innerWidth||this.$window.width()}getScreenHeight(){return this.isAppleDevice()?this.getAppleScreenHeight():window.innerHeight||this.$window.height()}getOperatingSystem(){var e;let i=["windows","mac","linux","windowsphone","chromeos","android","ios","blackberry","firefoxos","webos","bada","tizen","sailfish"].find(e=>t[e])||"";return""===i&&(e=navigator.platform.toLowerCase().match(/win|mac|linux/),i=(i="win"===(i=e?e[0]:i)?"windows":i)||"PlatformUnknown"),i}getRenderingEngine(){return["webkit","blink","gecko","msie","msedge"].find(e=>t[e])||""}isAppleDevice(){return/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.MSStream}getAppleScreenWidth(){return"chrome"!==this.browser&&90===Math.abs(window.orientation)?document.documentElement.clientHeight:document.documentElement.clientWidth}getAppleScreenHeight(){return"chrome"!==this.browser&&90===Math.abs(window.orientation)?document.documentElement.clientWidth:document.documentElement.clientHeight}getAppleDeviceType(){return["iphone","ipad","ipod"].find(e=>t[e])||""}pixelDensity(){var e=window.devicePixelRatio||1;return 3<=e?"ultra-high":2<=e?"high":1.5<=e?"medium":"low"}}return e});